#!/usr/bin/env node
// Self-hosted fonts (#110, #114): builds the woff2 files in src/lib/fonts/ and fonts.css from the
// Fontsource fonts, keeping only what the site uses. Each palette has its own text face (#114);
// a browser only downloads the faces the current palette uses.
//
// - Text faces: weight 400–600 (italic 400 only), optical size 12–48 where the font has that axis
//   (text-xs to the largest heading; the browser picks the optical size from the font size).
// - Each text style is split by unicode-range: a core file (ASCII and the punctuation the site
//   uses) and the rest of Latin, which a browser only downloads for a page that needs it.
// - Space Mono (code, every palette): 400 and 700, Latin. It has no other weights.
// - "<Family> Fallback": Georgia or Arial scaled to the face's metrics (Capsize), so the swap from
//   the system font moves the text as little as possible.
//
//   pnpm fonts     # after changing a range, the characters, a family, or a Fontsource version

import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { createFontStack } from '@capsizecss/core';
import arial from '@capsizecss/metrics/arial';
import georgia from '@capsizecss/metrics/georgia';
import instrumentSans from '@capsizecss/metrics/instrumentSans';
import literata from '@capsizecss/metrics/literata';
import newsreader from '@capsizecss/metrics/newsreader';
import schibstedGrotesk from '@capsizecss/metrics/schibstedGrotesk';
import workSans from '@capsizecss/metrics/workSans';
import subsetFont from 'subset-font';

const OUT = 'src/lib/fonts';

/** Google Fonts' "latin" subset: what the site served before #110. */
const LATIN = [
	[0x0000, 0x00ff],
	[0x0131],
	[0x0152, 0x0153],
	[0x02bb, 0x02bc],
	[0x02c6],
	[0x02da],
	[0x02dc],
	[0x0304],
	[0x0308],
	[0x0329],
	[0x2000, 0x206f],
	[0x20ac],
	[0x2122],
	[0x2191],
	[0x2193],
	[0x2212],
	[0x2215],
	[0xfeff],
	[0xfffd]
];

/** Printable ASCII plus the punctuation in the site's own copy (· – — … © arrows) and quotes. */
const CORE = [
	[0x0020, 0x007e],
	[0x00a0],
	[0x00a9],
	[0x00b7],
	[0x00d7],
	[0x00e9],
	[0x2013, 0x2014],
	[0x2018, 0x2019],
	[0x201c, 0x201d],
	[0x2022],
	[0x2026],
	[0x20ac],
	[0x2190, 0x2193]
];

const expand = (ranges) =>
	ranges.flatMap(([a, b = a]) => [...Array(b - a + 1)].map((_, i) => a + i));
const core = new Set(expand(CORE));
const rest = expand(LATIN).filter((c) => !core.has(c) && c >= 0x20);

/** Code points as a CSS unicode-range, runs merged. */
function unicodeRange(codes) {
	const sorted = [...new Set(codes)].sort((a, b) => a - b);
	const runs = [];
	for (const c of sorted) {
		const last = runs.at(-1);
		if (last && c === last[1] + 1) last[1] = c;
		else runs.push([c, c]);
	}
	const hex = (c) => c.toString(16).toUpperCase().padStart(4, '0');
	return runs.map(([a, b]) => (a === b ? `U+${hex(a)}` : `U+${hex(a)}-${hex(b)}`)).join(', ');
}

const text = (codes) => String.fromCodePoint(...codes);
const variable = (pkg, file) =>
	readFileSync(`node_modules/@fontsource-variable/${pkg}/files/${pkg}-latin-${file}.woff2`);

const SERIF = { metrics: georgia, local: ['Georgia', 'Georgia Italic'] };
const SANS = { metrics: arial, local: ['Arial', 'Arial Italic'] };

/**
 * Each palette's text face (#114). `slug` names the files; `axis` is the Fontsource file with
 * the axes we keep (`opsz` = weight and optical size, `wght` = weight only).
 */
export const TEXT_FACES = [
	{ family: 'Newsreader', slug: 'newsreader', axis: 'opsz', metrics: newsreader, fallback: SERIF },
	{
		family: 'Instrument Sans',
		slug: 'instrument-sans',
		axis: 'wght',
		metrics: instrumentSans,
		fallback: SANS
	},
	{ family: 'Literata', slug: 'literata', axis: 'opsz', metrics: literata, fallback: SERIF },
	{
		family: 'Schibsted Grotesk',
		slug: 'schibsted-grotesk',
		axis: 'wght',
		metrics: schibstedGrotesk,
		fallback: SANS
	},
	{ family: 'Work Sans', slug: 'work-sans', axis: 'wght', metrics: workSans, fallback: SANS }
];

rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });
const css = [
	'/* Generated by `pnpm fonts` (scripts/fonts.mjs, #110, #114). Edit the script, not this file. */'
];
let total = 0;

async function write(name, file, face) {
	writeFileSync(`${OUT}/${name}.woff2`, file);
	total += file.length;
	console.log(`${name}.woff2: ${(file.length / 1024).toFixed(1)} KB`);
	css.push(`@font-face {
	font-family: '${face.family}';
	font-style: ${face.style};
	font-weight: ${face.weight};
	font-display: swap;
	src: url('./${name}.woff2') format('woff2');
	unicode-range: ${unicodeRange(face.codes)};
}`);
}

for (const face of TEXT_FACES) {
	const opsz = face.axis === 'opsz' ? { opsz: { min: 12, max: 48 } } : {};
	for (const [style, weight, wght] of [
		['normal', '400 600', { min: 400, max: 600 }],
		['italic', '400', 400]
	]) {
		const src = variable(face.slug, `${face.axis}-${style}`);
		const name = `${face.slug}-${style === 'normal' ? 'roman' : 'italic'}`;
		for (const [part, codes] of [
			['core', [...core]],
			['rest', rest]
		]) {
			const file = await subsetFont(src, text(codes), {
				targetFormat: 'woff2',
				variationAxes: { wght, ...opsz }
			});
			await write(`${name}-${part}`, file, { family: face.family, style, weight, codes });
		}
	}

	// The system font scaled to this face, for normal and italic text while it loads.
	const { fontFaces } = createFontStack([face.metrics, face.fallback.metrics], {
		fontFaceFormat: 'styleString'
	});
	const overrides = fontFaces
		.match(/\{([^}]*)\}/)[1]
		.replace(/\s*(src|font-family):[^;]*;/g, '')
		.trim();
	face.fallback.local.forEach((local, i) => {
		css.push(`@font-face {
	font-family: '${face.family} Fallback';
	font-style: ${i === 0 ? 'normal' : 'italic'};
	src: local('${local}');
	${overrides.replace(/;\s*/g, ';\n\t').trim()}
}`);
	});
}

// Space Mono: static 400 and 700, the whole Latin subset in one file each.
for (const weight of [400, 700]) {
	const src = readFileSync(
		`node_modules/@fontsource/space-mono/files/space-mono-latin-${weight}-normal.woff2`
	);
	const file = await subsetFont(src, text(expand(LATIN)), { targetFormat: 'woff2' });
	await write(`space-mono-${weight}`, file, {
		family: 'Space Mono',
		style: 'normal',
		weight: String(weight),
		codes: expand(LATIN)
	});
}

writeFileSync(`${OUT}/fonts.css`, css.join('\n\n') + '\n');
console.log(`${OUT}/fonts.css · ${(total / 1024).toFixed(0)} KB of fonts in all`);
