#!/usr/bin/env node
// Self-hosted fonts (#110): builds the woff2 files in src/lib/fonts/ and fonts.css from the
// Fontsource variable fonts, keeping only what the site uses, so pages look exactly as they did
// with Google Fonts at about half the bytes.
//
// - Newsreader: weight 400–600 (italic 400 only, as before), optical size 12–48 (text-xs to the
//   largest heading; the browser picks the optical size from the font size).
// - Each Newsreader style is split by unicode-range: a core file (ASCII and the punctuation the
//   site uses) and the rest of Latin, which a browser only downloads for a page that needs it.
// - JetBrains Mono (code): weight 400–500, Latin.
// - "Newsreader Fallback": Georgia scaled to Newsreader's metrics (Capsize), so the swap from the
//   system serif to Newsreader moves the text as little as possible.
//
//   pnpm fonts     # after changing a range, the characters, or a Fontsource version

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { createFontStack } from '@capsizecss/core';
import georgia from '@capsizecss/metrics/georgia';
import newsreader from '@capsizecss/metrics/newsreader';
import subsetFont from 'subset-font';

const OUT = 'src/lib/fonts';

/** Google Fonts' "latin" subset: what the site served before #110. */
const LATIN = [
	[0x0000, 0x00ff],
	[0x0131],
	[0x0152, 0x0153],
	[0x02bb, 0x02bc],
	[0x02c6],
	[0x02da],
	[0x02dc],
	[0x0304],
	[0x0308],
	[0x0329],
	[0x2000, 0x206f],
	[0x20ac],
	[0x2122],
	[0x2191],
	[0x2193],
	[0x2212],
	[0x2215],
	[0xfeff],
	[0xfffd]
];

/** Printable ASCII plus the punctuation in the site's own copy (· – — … © arrows) and quotes. */
const CORE = [
	[0x0020, 0x007e],
	[0x00a0],
	[0x00a9],
	[0x00b7],
	[0x00d7],
	[0x00e9],
	[0x2013, 0x2014],
	[0x2018, 0x2019],
	[0x201c, 0x201d],
	[0x2022],
	[0x2026],
	[0x20ac],
	[0x2190, 0x2193]
];

const expand = (ranges) =>
	ranges.flatMap(([a, b = a]) => [...Array(b - a + 1)].map((_, i) => a + i));
const core = new Set(expand(CORE));
const rest = expand(LATIN).filter((c) => !core.has(c) && c >= 0x20);

/** Code points as a CSS unicode-range, runs merged. */
function unicodeRange(codes) {
	const sorted = [...new Set(codes)].sort((a, b) => a - b);
	const runs = [];
	for (const c of sorted) {
		const last = runs.at(-1);
		if (last && c === last[1] + 1) last[1] = c;
		else runs.push([c, c]);
	}
	const hex = (c) => c.toString(16).toUpperCase().padStart(4, '0');
	return runs.map(([a, b]) => (a === b ? `U+${hex(a)}` : `U+${hex(a)}-${hex(b)}`)).join(', ');
}

const text = (codes) => String.fromCodePoint(...codes);
const source = (pkg, file) =>
	readFileSync(`node_modules/@fontsource-variable/${pkg}/files/${file}`);

const FACES = [
	{
		family: 'Newsreader',
		style: 'normal',
		weight: '400 600',
		src: source('newsreader', 'newsreader-latin-opsz-normal.woff2'),
		axes: { wght: { min: 400, max: 600 }, opsz: { min: 12, max: 48 } },
		parts: { 'newsreader-roman-core': [...core], 'newsreader-roman-rest': rest }
	},
	{
		family: 'Newsreader',
		style: 'italic',
		weight: '400',
		src: source('newsreader', 'newsreader-latin-opsz-italic.woff2'),
		axes: { wght: 400, opsz: { min: 12, max: 48 } },
		parts: { 'newsreader-italic-core': [...core], 'newsreader-italic-rest': rest }
	},
	{
		family: 'JetBrains Mono',
		style: 'normal',
		weight: '400 500',
		src: source('jetbrains-mono', 'jetbrains-mono-latin-wght-normal.woff2'),
		axes: { wght: { min: 400, max: 500 } },
		parts: { 'jetbrains-mono': expand(LATIN) }
	}
];

mkdirSync(OUT, { recursive: true });
const css = [
	'/* Generated by `pnpm fonts` (scripts/fonts.mjs, #110). Edit the script, not this file. */'
];

for (const face of FACES) {
	for (const [name, codes] of Object.entries(face.parts)) {
		const file = await subsetFont(face.src, text(codes), {
			targetFormat: 'woff2',
			variationAxes: face.axes
		});
		writeFileSync(`${OUT}/${name}.woff2`, file);
		console.log(`${name}.woff2: ${(file.length / 1024).toFixed(1)} KB`);
		css.push(`@font-face {
	font-family: '${face.family}';
	font-style: ${face.style};
	font-weight: ${face.weight};
	font-display: swap;
	src: url('./${name}.woff2') format('woff2');
	unicode-range: ${unicodeRange(codes)};
}`);
	}
}

// Georgia scaled to Newsreader, for normal and italic text while Newsreader loads.
const { fontFaces } = createFontStack([newsreader, georgia], { fontFaceFormat: 'styleString' });
const overrides = fontFaces
	.match(/\{([^}]*)\}/)[1]
	.replace(/\s*(src|font-family):[^;]*;/g, '')
	.trim();
for (const [style, local] of [
	['normal', 'Georgia'],
	['italic', 'Georgia Italic']
]) {
	css.push(`@font-face {
	font-family: 'Newsreader Fallback';
	font-style: ${style};
	src: local('${local}');
	${overrides.replace(/;\s*/g, ';\n\t').trim()}
}`);
}

writeFileSync(`${OUT}/fonts.css`, css.join('\n\n') + '\n');
console.log(`${OUT}/fonts.css`);
